### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by montogeek** [php-fig/php-fig.github.com#147]
The current design is not _good_, it needs a redesign.
Maybe some help from https://twitter.com/reinink who designed @thephpleague site

**Comment by philsturgeon** [comment]
The redesign is well under way as of about a year ago, but it's hit some roadblocks.

**Comment by montogeek** [comment]
I can help implementing it

**Comment by reinink** [comment]
This is [happening](https://github.com/reinink/php-fig.github.com).

**Comment by montogeek** [comment]
Let me know how I can help!

**Comment by reinink** [comment]
@montogeek Thanks! I think I am okay for now.

**Comment by reinink** [comment]
You can follow my progress here: http://php-fig.reinink.ca

**Comment by montogeek** [comment]
Looks great!

**Comment by michaelcullum** [comment]
@reinink Whatever happened with this?

**Comment by reinink** [comment]
@michaelcullum It's still going to happen! :)

**Comment by reinink** [comment]
See #161.

**Comment by reinink** [comment]
@philsturgeon This can be closed now.
