### ISSUE TITLE
"Other" section for new homepage

### ISSUE THREAD

**Issue by philsturgeon** [php-fig/php-fig.github.com#162]
The new homepage ( #161 ) has a few categories for PSRs, which some will not fall into. 

That's fair, as those popped up since the designing started, but we need an "Other" or "Miscellaneous" section to house those for now. We can add fresh categories if enough "Other" pop up, but for now it seems fair enough.

**Comment by michaelcullum** [comment]
We will need this shortly as PSR-13 will be going into Review soon. @reinink

**Comment by reinink** [comment]
This shouldn't take too much to add.

**Comment by stefanotorresi** [comment]
Closing this for now since relevant PSRs (5, 9, 10) are abandoned for inactivity.
