### ISSUE TITLE
Roles are not defined

### ISSUE THREAD

**Issue by staabm** [php-fig/php-fig.github.com#176]
The roles which I can find on http://www.php-fig.org/psr/ seem not to be described anywhere.

What is the responsibility of..
- Editor
- Coordinator
- Sponsor

..? I guess this should be described on the website

**Comment by staabm** [comment]
I just was pointed to https://github.com/php-fig/fig-standards/blob/master/bylaws/004-psr-workflow.md

I propose that the document should be crosslinked from the above mentioned site

**Comment by michaelcullum** [comment]
https://github.com/php-fig/fig-standards/pull/705
