### ISSUE TITLE
PSR6 link does not work

### ISSUE THREAD

**Issue by sameg14** [php-fig/php-fig.github.com#178]
http://www.php-fig.org/psr/psr-6/

![fullscreen_12_16_15__3_24_pm](https://cloud.githubusercontent.com/assets/76828/11854369/1e3c4094-a409-11e5-8527-e48c511c2021.png)

**Comment by cyberwolf** [comment]
Indeed gives a 404.

**Comment by michaelcullum** [comment]
Yes, that's because it needs adding to the site.

**Comment by dragoonis** [comment]
I've added PSR-6 to the website. The fig submodule is out of date, and needs updated to commit `c9379057e9b29676cb421187b165f8a4e8814927`

I tried to update it myself but my git was acting strange.

Can someone please make a PR updating the fig submodule and ping my name so I can merge it ?

Thanks. /cc @reinink @philsturgeon

**Comment by philsturgeon** [comment]
Almost got it done. Let's see how well this train wifi does.

**Comment by philsturgeon** [comment]
There we go! https://github.com/php-fig/php-fig.github.com/pull/180
