### ISSUE TITLE
Translations need removing

### ISSUE THREAD

**Issue by michaelcullum** [php-fig/php-fig.github.com#187]

**Comment by michaelcullum** [comment]
So they have been removed from showing but we continue to have a translations box and some translations stuff in the build script. I have to confess I don't know how all that works so...

**Comment by jhonmike** [comment]
but community can activate the translation?

**Comment by michaelcullum** [comment]
Please clarify what you mean?

**Comment by jhonmike** [comment]
I can translate the website to Portuguese Brazil?

**Comment by reinink** [comment]
This shouldn't take much to remove. Leave it with me.

**Comment by stefanotorresi** [comment]
done in #230
