### ISSUE TITLE
Fix Jekyll Build Warnings

### ISSUE THREAD

**Issue by michaelcullum** [php-fig/php-fig.github.com#191]
> The page build completed successfully, but returned the following warning:
> 
> You are currently using the 'redcarpet' Markdown engine, which will not be supported on GitHub Pages after May 1st. At that time, your site will use 'kramdown' for markdown rendering instead. To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown processor-to-kramdown.

**Comment by reinink** [comment]
Yes, and we have more issues:

> The page build completed successfully, but returned the following warning:

> You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml' and ensure the 'pygments' key is unset. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

Yes, we really need to do this. Unfortunately, it also means a lot of changes to the [https://github.com/php-fig/fig-standards](fig-standards) repo. The backticks are no longer supported, we have to use tildes instead.

![image](https://cloud.githubusercontent.com/assets/882133/15413874/a71b3208-1e02-11e6-819a-8cb23322ae67.png)

**Comment by rob006** [comment]
> The backticks are no longer supported, we have to use tildes instead.

It should be possible to fix by changing the jekyll configuration: 
http://stackoverflow.com/a/35348119/5812455

**Comment by kboygit** [comment]
I dont seem quite to understand this error on markdown and pygments syntax highlighting can somebody walk me through this stuff and let me understand it fully?.



```
You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml' and ensure the 'pygments' key is unset. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.
```

**Comment by jknopp** [comment]
@kboygit this has been addressed by Github here:
- https://help.github.com/articles/using-syntax-highlighting-on-github-pages/
- https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors

> Rouge is Jekyll's default syntax highlighter and is compatible with the Pygments highlighter. If Pygments is set in your _config.yml file then your pages site will automatically build with Rouge as the default highlighter instead

**Comment by kboygit** [comment]
This has been solved a long time thanks
