### ISSUE TITLE
Code Highlighting

### ISSUE THREAD

**Issue by AndrewCarterUK** [php-fig/php-fig.github.com#207]
I think the PHP code highlighting isn't working because the code examples in the PSRs don't start with '<?php'.

There is (apparently) an option in Jekyll with pygments to set a ['startinline' flag](https://github.com/jekyll/jekyll/issues/1633) - though this looks like it requires modifying the snippets in the PSR documents.

Opening this up for discussion because I don't fancy doing a bunch or work that'll never get merged if people aren't happy to go down that route. Open to other ideas and happy to invest time in this.

**Comment by reinink** [comment]
Hey Andrew, can you give an example? Are you talking about the blocks? Because it seems like many of those do start with `<?php`. However the inline code snippets don't. Not sure how that would be done.

**Comment by AndrewCarterUK** [comment]
Pretty much all the PHP examples on this page don't get highlighted: http://www.php-fig.org/psr/psr-7/

**Comment by reinink** [comment]
Yeah, good call. A bunch of the PSRs do include this, and a bunch don't. I think the best thing to do is loop back and patch the blocks that don't and simply add an opening PHP tag. If you want to do that, cool, otherwise just let me know and I'll add it to my list.

**Comment by AndrewCarterUK** [comment]
I'm happy to do it, I think there is a difference between:

```php
$message = $message->withHeader('foo', 'bar');

echo $message->getHeaderLine('foo');
// Outputs: bar

echo $message->getHeaderLine('FOO');
// Outputs: bar

$message = $message->withHeader('fOO', 'baz');
echo $message->getHeaderLine('foo');
// Outputs: baz
```

And:

```php
<?php

$message = $message->withHeader('foo', 'bar');

echo $message->getHeaderLine('foo');
// Outputs: bar

echo $message->getHeaderLine('FOO');
// Outputs: bar

$message = $message->withHeader('fOO', 'baz');
echo $message->getHeaderLine('foo');
// Outputs: baz
```

Maybe if I did it like this:

```php
<?php

// ...

$message = $message->withHeader('foo', 'bar');

echo $message->getHeaderLine('foo');
// Outputs: bar

echo $message->getHeaderLine('FOO');
// Outputs: bar

$message = $message->withHeader('fOO', 'baz');
echo $message->getHeaderLine('foo');
// Outputs: baz
```

Or am I over thinking things?

**Comment by reinink** [comment]
I think you're maybe overthinking it. :)

I'd just add the opening tags. Thanks Andrew! 👍
