### ISSUE TITLE
Fix incorrect markup on home page

### ISSUE THREAD

**Issue by reinink** [php-fig/php-fig.github.com#221]
A PR (https://github.com/php-fig/php-fig.github.com/pull/217) was pulled in to fix the markup on the home page. I've since reverted it (https://github.com/php-fig/php-fig.github.com/pull/220) because it has some negative side affects. However, this should still be fixed. I'll do this when I have a minute.

**Comment by stefanotorresi** [comment]
fixed in 5b41f5f
