### ISSUE TITLE
Problem with external fonts - page loading stalls for 5 to 15s

### ISSUE THREAD

**Issue by szywo** [php-fig/php-fig.github.com#223]
It seems that this is more network config issue than page source error, but it is still an issue.

In  [_sass/base/defaults.scss](https://github.com/php-fig/php-fig.github.com/blob/master/_sass/base/defaults.scss) there are problems with import:
```@import "//cloud.typography.com/6655974/614628/css/fonts.css";```
it responds with status code 302 and redirects to:
```http://fonts.php-fig.org/fonts/418709/C505776BD56D30D0B.css```
which stalls page loading process for 5 to 15 seconds

DNS lookup for this domain returns:
```fonts.php-fig.org.	1800	IN	CNAME	phpfig.distill.ca.```
but 
`phpfig.distill.ca`
can not be resolved and the same with `dns.jomax.net` server pointed as authoritative.

**Comment by reinink** [comment]
Good call, thanks. I need to disconnect my personal DNS from this. That's why this happened.

I've added a record back in, which should fix this shortly,

@michaelcullum Who controls the DNS for php-fig.org? I'd like to get some changes made for this! Thanks.

**Comment by michaelcullum** [comment]
I do, where do we need to point it?

**Comment by reinink** [comment]
Hey Michael! An `A` record that points to `45.79.179.92` will do it.

```
A    fonts.php-fig.org    45.79.179.92
```

**Comment by szywo** [comment]
Thanks, it is much better now. And custom fonts load as expected. 
However I would recommend using a fall-back fonts at least in `.home_banner__title` and `.home_banner__links` because without it (in case of error in fonts loading) those sections are rendered with default font which in most cases is _serif_. In normal (pc) view _serif_ (_sans_ also) is too wide and pushes part of intro and links below `.home_banner` bottom boundary. I suggest:
`font-family: 'Tungsten A', 'Tungsten B', 'Liberation Sans Narrow', 'Arial Narrow', 'Helvetica Narrow', sans-serif;`
I know these fall-back fonts are not _"interesting"_ but at least condensed enough not to break banner look in case something went wrong.

**Comment by reinink** [comment]
Great idea @szywo! Want to put a PR together? :)

**Comment by szywo** [comment]
@reinink PR? Pull Reqest? sorry I'm newbie on github and also not feel experienced enough to mess with site building code. Just tracked down problem that appeared in my browser comparing site look with and without fonts loaded. Thanks.

ps. Besides I'm already late on my own work.

**Comment by stefanotorresi** [comment]
fixed in #230 by switching to Google Fonts.
