### ISSUE TITLE
PSR Includes are out of date

### ISSUE THREAD

**Issue by oshlifeworks** [php-fig/php-fig.github.com#231]
There's been a change that makes a link to PSR-15 not working any more (it's been renamed from _middleware_ to _handlers_ PSR). The relevant PR: https://github.com/php-fig/fig-standards/pull/954
I located this to be in the [_includes/](https://github.com/php-fig/php-fig.github.com/tree/master/_includes) directory, where it's pointing to a revision in the fig-standards repo, however I never came across this before and I'm not sure how to update the revision.

**Comment by oshdev** [comment]
I have attempted to fix this in the referenced PR. I never worked with git submodules, so double check it please ;]
